trigger: none

pr: none

variables:
- name: devEnvironment
  value: dev
# TODO: provide an email address for the ExampleWorkflow to an send mail to
- name: toEmailAddress
  value: ''

resources:
  pipelines:
  - pipeline: cipipeline
    # TODO: Update with the name of your CI pipeline
    source: ''
    trigger:
      branches:
      - main

stages:
- stage: DEV
  displayName: 'DEV Deployment'
  variables:
  - template: variables/pipeline-vars.yml
  jobs:
  - deployment: deploy_logicapp_resources
    displayName: Deploy Logic App
    pool:
      vmImage: ubuntu-18.04
    environment: $(devEnvironment)
    variables:
      deploymentMode: 'Incremental'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureFunctionApp@1
            displayName: 'Deploy logic app workflows'
            inputs:
              azureSubscription: 'Microsoft Azure Internal Consumption (ea3e783f-6b4a-4e74-b379-9fa512da2b7f)'
              appType: 'functionApp'
              appName: 'LAStdEx1'
              package: '$(System.DefaultWorkingDirectory)/azure-devops-sample/Local Projects.zip'
              deploymentMethod: 'zipDeploy'
